name: Lint
on:
  push:
    branches:
      - "*" # Run on every branch
  pull_request:
    branches:
      - "*" # Run on every pull request

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18] # Specify Node.js version here
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint # Replace with your linting script or command
