name: audit pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"
      - "release"

jobs:
  audit:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm audit
