name: dockerhub pipeline

on:
  push:
    branches:
      - "release"

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #login to DockerHub without exposing secrets stored in github-env to log-files
      - run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/web-app:latest .
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-app:latest
